### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by andryblack** [Andy-Big/MKS-DLP-alter#1]
Can you provide installation instruction? How to prepare ui images installation folder?

**Comment by Andy-Big** [comment]
I am very sorry for the late reply. In recent days, I have been very busy at work :( I will answer you in detail in 2-3 days. In short: you need to put the binary in the root of the flash drive, images in certain folders of the flash drive, insert the flash drive into the board and reboot it. The native bootloader will start updating the firmware and after After its completion, the firmware will automatically load pictures from the corresponding folders at startup.

**Comment by andryblack** [comment]
I am already got all needed for me information from source code, you can see it at Makefile rule *distr* at my PR. 
But I think it should be documented.

**Comment by Andy-Big** [comment]
Finally I got there, made instructions for updating the firmware and at the same time prepared a release :)
