### ISSUE TITLE
Stuck on the Screensaver

### ISSUE THREAD

**Issue by kanawati975** [Andy-Big/MKS-DLP-alter#4]
uploading was successful with no issues, but after booting for the first time, the screensaver (big clock) is on the screen and I couldn't get out of it.
Any tips and suggestions will be appreciated.

**Comment by dpjewellerystudio** [comment]
![0](https://user-images.githubusercontent.com/52852077/110198949-d5ff8e80-7e0a-11eb-98ac-6a45e3ab5625.jpg)

**Comment by dpjewellerystudio** [comment]
cimg

**Comment by socalschi** [comment]
I? Having the same problem, i for stucked on click, any Idea How to solve this?!

**Comment by Andy-Big** [comment]
In screensaver mode, the controller slows down a lot, so it can react very slowly to pressing. Try to keep pressing the display for 0.5-1 seconds.

**Comment by socalschi** [comment]
Theres any way to remove this clock?! I've try to press the screen for 10sec and nothing

**Comment by Andy-Big** [comment]
This is very strange, I have not noticed this either on 1.1 or 2.0 boards. The screensaver can be disabled altogether. To do this, set the _screensaver_time_ parameter to 0 in the _settings.acfg_ configuration file. And "print" this settings file for the changes to take effect.

**Comment by socalschi** [comment]
Dude, i recorded the process

https://youtu.be/vKosBV0o0ps

**Comment by socalschi** [comment]
i know this is a little bit weird, but can u make a file with your config to 2.0 board? so i try this file, because idk if i'm doing something wrong, i already try even the 0.8 version and got same error

**Comment by Andy-Big** [comment]
Whoa! I just performed all the same operations as you in the video and I have the same problem! 😳
Well, now that it was repeated with me, it will be much easier for me to find the reason. In the next day or two, I think I will fix it :)

**Comment by Andy-Big** [comment]
Version 0.8 should not be used yet, it is now in the process of adding a Chita board and an interface for 320x240 displays to it, so at the moment there may be a whole bunch of problems in it. In general, there are definitely two problems in it, which I know :) But there may be more of them. It can be used when I finish adding a new board and verify that everything works on all board revisions. Then I'll post it in releases :)

**Comment by socalschi** [comment]
Bu

> Whoa! I just performed all the same operations as you in the video and I have the same problem! 😳
> Well, now that it was repeated with me, it will be much easier for me to find the reason. In the next day or two, I think I will fix it :)

But i made something different on installation?! Any Idea?

**Comment by Andy-Big** [comment]
I found the reason - just my stupid mistake in the code for handling screensaver time. Because of this error, it cannot be set to 0 in the settings, otherwise such nonsense starts with a non-removable screensaver. In version 0.08 I will fix this error, but for now there is a way to get rid of it.
If you have such a situation with a non-removable screensaver, then you need to update the firmware to a lower version. For example, for version 0.05. Just update as described in the instructions - upload the contents of the archive to the flash drive, insert the flash drive into the printer and reboot it. After the update, the firmware should work fine. Now you can again upload version 0.07 to the flash drive and update it. After that, she should also work normally.
The main thing after that is not to set the _screensaver_time_ parameter to 0 in the _settings.acfg_ configuration file.
Now I'm loading a video demonstrating this whole process. As soon as it loads, I will add a link to it.

**Comment by socalschi** [comment]
ty dude

> 
> 
> I found the reason - just my stupid mistake in the code for handling screensaver time. Because of this error, it cannot be set to 0 in the settings, otherwise such nonsense starts with a non-removable screensaver. In version 0.08 I will fix this error, but for now there is a way to get rid of it.
> If you have such a situation with a non-removable screensaver, then you need to update the firmware to a lower version. For example, for version 0.05. Just update as described in the instructions - upload the contents of the archive to the flash drive, insert the flash drive into the printer and reboot it. After the update, the firmware should work fine. Now you can again upload version 0.07 to the flash drive and update it. After that, she should also work normally.
> The main thing after that is not to set the _screensaver_time_ parameter to 0 in the _settings.acfg_ configuration file.
> Now I'm loading a video demonstrating this whole process. As soon as it loads, I will add a link to it.

**Comment by Andy-Big** [comment]
https://www.youtube.com/watch?v=U_eCy2t2BZw

**Comment by Andy-Big** [comment]
Uploaded fixed binaries to all releases, so now this error will not appear initially.
Thanks everyone for pointing out this error :)

**Comment by socalschi** [comment]
> 
> 
> Uploaded fixed binaries to all releases, so now this error will not appear initially.
> Thanks everyone for pointing out this error :)

working like a charm, jod job!!

**Comment by Andy-Big** [comment]
Cool! :)
